---
title: "ABS vs correlation trend"
subtitle: ''
author: "Developed by [Gabriel Hoffman](http://gabrielhoffman.github.io/)"
date: "Run on `r Sys.time()`"
documentclass: article
output: 
  html_document:
  toc: true
  smart: false
---



<!---

cd /hpc/users/hoffmg01/work/microglia_analysis
# rm -rf MOFA2_cache/
ml git pandoc R/4.0.3
git pull
R

system("git pull")


rmarkdown::render("ABC_trend.Rmd")

--->


```{r setup, include=FALSE}
suppressPackageStartupMessages({
library(synapser)
library(ggplot2)
library(tidyverse)
library(kableExtra)
library(cowplot)
synLogin()
})

knitr::opts_chunk$set(
  echo = FALSE,
  warning=FALSE,
  message=FALSE,
  error = FALSE,
  tidy = FALSE,
  cache = TRUE)
```


```{r make.plot, fig.width=5, fig.height=5}

df = readRDS(synGet('syn25014476')$path)
df$distance = abs(df$PeakToGene_dist)
df$distance.log10 = log10(abs(df$PeakToGene_dist))

xmax = 5.6e5

fig1 = ggplot(df, aes(distance, abs(Spearman_Rho), color=ABCscore > 0.02)) + geom_smooth(method="gam") + theme_classic() + theme(legend.position = "none") + scale_color_manual(values=c("blue", "red")) + scale_x_log10(limits=c(500,xmax), expand=c(0,0))

fig2 = ggplot(df, aes(distance, color=ABCscore > 0.02)) + geom_density() + theme_classic() + theme(legend.position = "none") + scale_color_manual(values=c("blue", "red")) + scale_x_log10(limits=c(500,xmax), expand=c(0,0)) 

plot_grid(fig1, fig2, ncol=1, align='hv', rel_heights=c(1, .3))
```

```{r compare.curves}
# Compute the curves fit by geom_smooth(method="gam")
# Evaluate for Category A and B separately
fitA = mgcv::gam( abs(Spearman_Rho) ~ s(distance.log10, bs = "cs"), data=df[df$ABCscore > 0.02,])

fitB = mgcv::gam( abs(Spearman_Rho) ~ s(distance.log10, bs = "cs"), data=df[df$ABCscore <= 0.02,])

# Evaluate the new curves at a range of values
dist.array = c(5000, 10000, 20000, 50000, 100000, 250000, 500000)
values = sort(c(seq(500, xmax, length.out=1000), dist.array))
df_new = data.table(distance = values, distance.log10 = log10(values))

# Get the predicted correlation and the standard error for reach distance
predA = predict(fitA, df_new, se.fit=TRUE)
predB = predict(fitB, df_new, se.fit=TRUE)

# Evaluate the difference in correlation (beta), get the z-statistics (zstat)
# and evalute a 1 sided p-value testing if corr in A > corr in B
df_new$beta = (predA$fit - predB$fit)
df_new$zstat = (predA$fit - predB$fit) / sqrt(predA$se.fit^2 + predB$se.fit^2)
df_new$p.value = pnorm(df_new$zstat, lower.tail=FALSE)

ggplot(df_new, aes(distance.log10, zstat)) + geom_line() + theme_classic() + theme(aspect.ratio=1)
```

```{r table}
df_new[distance %in% dist.array,] %>% 
  mutate(p.value = format(p.value, scientific=TRUE, digits=3)) %>% 
  kable(caption="pi1 within dataset") %>% 
  kable_styling(full_width=FALSE)
```

















